name: 'Install dfx'
description: 'Install the dfx utility at a particular version'
inputs:
  dfx-version:
    description: >
      The dfx version to install. This value will be used to populate
      the DFX_VERSION variable that will be handled by the installation
      script "install.sh".
    default: 'latest'

runs:
  using: composite
  steps:
    - name: Set up environment
      if: inputs.dfx-version != 'latest'
      shell: sh
      run: |
        echo "DFX_VERSION=${{ inputs.dfx-version }}" >> $GITHUB_ENV
        echo "DFXVM_INIT_YES=true" >> $GITHUB_ENV
    - name: Install dfx
      shell: sh
      run: |
        echo "Version ${{ inputs.dfx-version }} will be installed"
        sh -ci "$(curl -fsSL https://raw.githubusercontent.com/dfinity/sdk/ens/update-setup-dfx-action/public/install-dfxvm.sh)"
