on:
  push:
    branches:
      - 'main'
      - ens/sdk-1547-1548-retry-and-notice-error
  pull_request:

jobs:
  # This job can be executed locally with the command `act -W .github/workflows/dfx-action.yml`
  test_dfx_action:
    runs-on: ${{ matrix.os }}
    name: Test the dfx action (action.yml)
    strategy:
      fail-fast: false
      matrix:
        a: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        b: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        os: [ ubuntu-latest, macos-latest ]
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      # Install a certain `dfx` version and check if it is properly installed
      - name: Install dfx
        uses: ./
      - name: Check if dfx is installed
        run: |
          dfx --version
