on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  # This job can be executed locally with the command `act -W .github/workflows/dfx-action.yml`
  test_dfx_action:
    runs-on: ${{ matrix.os }}
    name: Test the dfx action (action.yml)
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        include:
          - version: '0.11.1'
            expected-version: '0.11.1'
          - version: '0.14.1'
            expected-version: '0.14.1'
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          echo "Running on ${{ matrix.os }}"
          echo "Testing dfx version ${{ matrix.version }}"
          # create dfx.jsonb with dfx-json-dfx-version if set:
          if [ "${{ matrix.version }}" = "auto" ]; then
              echo "{\"dfx\": \"${{ matrix.dfx-json-dfx-version }}\"}" > dfx.json
          fi
      # Install a certain `dfx` version and check if it is properly installed
      - name: Install dfx
        uses: ./
        with:
          dfx-version: ${{ matrix.version }}
      - name: Check if the proper dfx version is installed
        run: |
          export
          
          actual_dfx_ver="$(dfx --version)"

          if [ -n "${{ matrix.expected-version }}" ]; then
              expected_dfx_ver="dfx ${{ matrix.expected-version }}"

              if [ "$actual_dfx_ver" != "$expected_dfx_ver" ]; then
                echo "Error: expected dfx version '$expected_dfx_ver', but '$actual_dfx_ver' found"
                exit 1
              fi
              echo "dfx version '$actual_dfx_ver' was installed correctly"
          else
              echo "dfx version '$actual_dfx_ver' was installed"
          fi

