on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/dfx-action.yml'
      - 'action.yml'
  pull_request:
    paths:
      - '.github/workflows/dfx-action.yml'
      - 'action.yml'

jobs:
  # This job can be executed locally with the command `act -W .github/workflows/dfx-action.yml`
  test_dfx_action:
    runs-on: ubuntu-latest
    name: Test the dfx action (action.yml)
    strategy:
      matrix:
        version: ['0.11.1', '0.14.1', '0.14.2-beta.2', 'latest']
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      # Install a certain `dfx` version and check if it is properly installed
      - name: Install dfx
        uses: ./
        with:
          dfx-version: ${{ matrix.version }}
      - name: Check if the proper dfx version is installed
        run: |
          actual_dfx_ver="$(dfx --version)"
          expected_dfx_ver="dfx ${{ matrix.version }}"

          if [ "$expected_dfx_ver" != "dfx latest" ]; then
            if [ "$actual_dfx_ver" != "$expected_dfx_ver" ]; then
              echo "Error: expected dfx version '$expected_dfx_ver', but '$actual_dfx_ver' found"
              exit 1
            fi

            echo "dfx version '$actual_dfx_ver' was installed correctly"
          else
            echo "The latest version is '$actual_dfx_ver'"
          fi
